# Generated by Django 3.1.7 on 2021-04-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Venda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total da Venda')),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('hora_venda', models.TimeField(auto_now_add=True)),
                ('data_hora_venda', models.DateTimeField(auto_now_add=True)),
                ('numero_venda', models.IntegerField(verbose_name='Número da venda')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('comprovante_venda', models.FileField(blank=True, null=True, upload_to='', verbose_name='Comprovante de venda')),
                ('exemplo_upload', models.FileField(blank=True, null=True, upload_to='outro_diretorio/')),
                ('venda_concluida', models.BooleanField()),
                ('quantidade_itens', models.IntegerField(blank=True, verbose_name='Quantidade de Itens')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestaoconstrucao.cliente')),
                ('produtos', models.ManyToManyField(to='gestaoconstrucao.Produto')),
            ],
        ),
    ]
