# Generated by Django 3.1.7 on 2021-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtoseletricos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(to='gestaoconstrucao.Produtoseletricos'),
        ),
    ]
