# Generated by Django 3.1.7 on 2021-04-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0003_auto_20210422_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Hidraulico',
        ),
    ]
