# Generated by Django 3.1.7 on 2021-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0005_auto_20210422_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.AddField(
            model_name='venda',
            name='Produtos1',
            field=models.ManyToManyField(to='gestaoconstrucao.Eletricos', verbose_name='Produtos Eletricos'),
        ),
        migrations.AddField(
            model_name='venda',
            name='Produtos2',
            field=models.ManyToManyField(to='gestaoconstrucao.Hidraulico', verbose_name='Produtos hidraulicos'),
        ),
    ]
