# Generated by Django 3.1.7 on 2021-04-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0006_auto_20210422_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletricos',
            name='valor',
        ),
    ]
