# Generated by Django 3.1.7 on 2021-04-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0007_remove_eletricos_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='exemplo_upload',
        ),
    ]
