# Generated by Django 3.1.7 on 2021-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0011_auto_20210422_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletricos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='hidraulico',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
