# Generated by Django 3.1.7 on 2021-04-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0012_auto_20210422_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='Produtos1',
        ),
        migrations.AddField(
            model_name='venda',
            name='Produtos1',
            field=models.ManyToManyField(to='gestaoconstrucao.Eletricos', verbose_name='Produtos Eletricos'),
        ),
    ]
