# Generated by Django 3.1.7 on 2021-04-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoconstrucao', '0013_auto_20210422_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade_itens',
        ),
    ]
